# Generated by Django 5.0.14 on 2025-05-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diamond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carat', models.FloatField()),
                ('cut', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=1)),
                ('clarity', models.CharField(max_length=10)),
                ('depth', models.FloatField()),
                ('table', models.FloatField()),
                ('price', models.IntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
        ),
    ]
